fos_rest:
    exception: true
    view:
        formats:
            json: true
            xml: true
        empty_content: 204
    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: json }
            - prefer_extension: false