nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://172.22.17.162:3000']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: []
        max_age: 3600
        hosts: []
        forced_allow_origin_value: ~
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
