vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        users:
            uri_prefix: /images/users
            upload_destination: '%kernel.project_dir%/public/images/users'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        chanels:
            uri_prefix: /images/chanels
            upload_destination: '%kernel.project_dir%/public/images/chanels'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

