version: "3.8"

services:
  alpine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_docker
    restart: always
    ports:
      - "9000:80"
    working_dir: /var/www/html/public/
    volumes:
      - ./src:/var/www/html/public/
    networks:
      - symfony
    depends_on:
      - db
      - mercure
      - php

  php:
    image: php:8.2-fpm
    container_name: php
    restart: always
    working_dir: /var/www/html/public/
    volumes:
      - ./src:/var/www/html/public/
    networks:
      - symfony

  db:
    image: mariadb:latest
    container_name: db
    restart: always
    ports:
      - "3306:80"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_: root
      MYSQL_DATABASE: chat2_db
    networks:
      - symfony
    volumes:
      - db-data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  mercure:
    image: dunglas/mercure
    container_name: mercure_docker
    restart: unless-stopped
    environment:
      SERVER_NAME: ":80"
      MERCURE_PUBLISHER_JWT_KEY: "!ChangeMe!"
      MERCURE_SUBSCRIBER_JWT_KEY: "!ChangeMe!"
      MERCURE_EXTRA_DIRECTIVES: cors_origins "http://localhost:3000"
    ports:
      - "9090:80"
      - "443:443"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8090:80
    volumes:
      - ./src:/var/www/
      - ./src/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - alpine

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - symfony

networks:
  symfony:
    driver: bridge

volumes:
  db-data:
