FROM caddy:latest

RUN apk add --no-cache ca-certificates

# Install Mercure
RUN wget -O /usr/local/bin/mercure https://github.com/dunglas/mercure/releases/download/v0.15.11/mercure_Linux_arm64.tar.gz \
    && chmod +x /usr/local/bin/mercure

CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
