nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:3000'] # specify your frontend origin
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
    paths:
        '^/': null
